name: CI

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - main
jobs:
  build:
    uses: ./.github/workflows/build.yml

  release: 
    if:  github.ref == 'refs/heads/main' && startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    needs: build
    uses: ./.github/workflows/release.yml
