name: Deploy

on:
 workflow_dispatch:
 workflow_call:

env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_NAME: hello-world

jobs:
  release:
    runs-on: ubuntu-latest
    name: Deploy container
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags

      - name: Download binary artifact
        uses: actions/download-artifact@v4
        with:
          name: hello-world
          path: ./bin

      - name: Build image
        run: podman build . -t ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Login with Podman
        run: podman login -u ${{ env.REGISTRY_USER }} -p ${{ env.REGISTRY_PASSWORD }} ghcr.io

      - name: Push image to GHCR
        run: podman push ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}
